<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     * Add share_purchase and share_sale transaction types to support share trading audit trail
     * Drops existing check constraint and creates new one with all valid transaction types
     */
    public function up()
    {
        // Only run for SQL Server (not for SQLite tests)
        if (DB::getDriverName() === 'sqlsrv') {
            // Drop the existing check constraint that was auto-generated by SQL Server
            DB::statement("ALTER TABLE transactions DROP CONSTRAINT [CK__transactio__type__1CDC41A7]");
            
            // Modify the column type to VARCHAR(50) to support all transaction types
            DB::statement("ALTER TABLE transactions ALTER COLUMN type VARCHAR(50) NOT NULL");
            
            // Add a new check constraint that includes share transaction types
            DB::statement("ALTER TABLE transactions ADD CONSTRAINT CK_transaction_types 
                CHECK (type IN ('saving_deposit', 'saving_withdrawal', 'loan_disbursement', 'repayment', 'share_purchase', 'share_sale'))");
        }
    }

    public function down()
    {
        // Only run for SQL Server (not for SQLite tests)
        if (DB::getDriverName() === 'sqlsrv') {
            // Drop the new constraint
            DB::statement("ALTER TABLE transactions DROP CONSTRAINT CK_transaction_types");
            
            // Recreate the original check constraint
            DB::statement("ALTER TABLE transactions ADD CONSTRAINT [CK__transactio__type__1CDC41A7] 
                CHECK (type IN ('saving_deposit', 'saving_withdrawal', 'loan_disbursement', 'repayment'))");
        }
    }
};
